package api

import (
	"context"
	"fmt"
	"net/http"
	"strings"
	"time"

	"flatline/internal/friction"
)

// The briefing (P18-4) is the corpus feeding the next session: one document,
// fetched at task start, assembled entirely from the refined layers — the
// working commands, the recurring friction with its mechanism and its mined
// endings, the files that hold the project's state. Every line is a recorded
// fact with its corroboration count; the calibers ride at the bottom so the
// reader — usually an agent — knows what each number is and is not.

const briefingRecurringLimit = 5
const briefingCommandsLimit = 10
const briefingFilesLimit = 5

const briefingNote = "本简报由 Flatline 从本机会话历史生成，逐条为记录到的事实并附佐证数，不是建议。口径：作业命令 = 同一规范化命令 ≥3 次运行且 ≥2 个会话，导航与等待类程序除外；机制来自封闭字典；“终结后动作”只陈述先后与对齐，不判定因果；热点文件按 read 记录计数。"

const briefingNoteEN = "Generated by Flatline from this machine's session history; every line is a recorded fact with its corroboration count, not advice. Calibers: a working command ran 3+ times across 2+ sessions, navigation and waiting programs excluded; mechanisms come from the closed dictionary; an ending action states sequence and alignment, never cause; hot files count read records."

type briefingRecurring struct {
	Signature    string  `json:"signature"`
	SampleLine   string  `json:"sample_line"`
	Sessions     int     `json:"sessions"`
	Count        int     `json:"count"`
	Mechanism    string  `json:"mechanism,omitempty"`
	MechanismEN  string  `json:"mechanism_en,omitempty"`
	TopEnding    string  `json:"top_ending,omitempty"`
	EndingScope  int     `json:"ending_sessions,omitempty"`
	LastAt       string  `json:"last_at,omitempty"`
	FrictionHref *string `json:"friction_href,omitempty"`
}

type briefingHotFile struct {
	Path     string `json:"path"`
	Reads    int    `json:"reads"`
	Sessions int    `json:"sessions"`
}

type briefingResponse struct {
	ProjectKey      string              `json:"project_key"`
	SessionsKnown   int                 `json:"sessions_known"`
	WorkingCommands []workingCommand    `json:"working_commands"`
	Recurring       []briefingRecurring `json:"recurring"`
	HotFiles        []briefingHotFile   `json:"hot_files"`
	GeneratedAt     string              `json:"generated_at"`
	Note            string              `json:"note"`
	NoteEN          string              `json:"note_en"`
	Complete        bool                `json:"complete"`
}

func (s *Server) handleProjectBriefing(w http.ResponseWriter, r *http.Request) {
	projectKey := r.PathValue("key")
	ctx := r.Context()
	briefing, err := s.assembleBriefing(ctx, projectKey)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	if r.URL.Query().Get("format") == "json" {
		writeJSON(w, http.StatusOK, briefing)
		return
	}
	w.Header().Set("Content-Type", "text/markdown; charset=utf-8")
	_, _ = w.Write([]byte(briefingMarkdown(briefing)))
}

func (s *Server) assembleBriefing(ctx context.Context, projectKey string) (briefingResponse, error) {
	out := briefingResponse{ProjectKey: projectKey,
		Recurring: []briefingRecurring{}, HotFiles: []briefingHotFile{},
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
		Note:        briefingNote, NoteEN: briefingNoteEN, Complete: true}

	if err := s.db.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM sessions WHERE project_key = ?`, projectKey).Scan(&out.SessionsKnown); err != nil {
		return out, err
	}

	knowledge, err := s.projectKnowledge(ctx, projectKey)
	if err != nil {
		return out, err
	}
	out.WorkingCommands = knowledge.WorkingCommands
	if len(out.WorkingCommands) > briefingCommandsLimit {
		out.WorkingCommands = out.WorkingCommands[:briefingCommandsLimit]
	}

	rows, err := s.db.QueryContext(ctx, `
		SELECT f.signature, COUNT(*), COUNT(DISTINCT f.session_id), MAX(f.occurred_at)
		FROM friction_records f JOIN sessions s ON s.id = f.session_id
		WHERE s.project_key = ? AND f.signature IS NOT NULL AND f.signature <> ''
		GROUP BY f.signature HAVING COUNT(DISTINCT f.session_id) >= 2
		ORDER BY COUNT(DISTINCT f.session_id) DESC, COUNT(*) DESC LIMIT ?`,
		projectKey, briefingRecurringLimit)
	if err != nil {
		return out, err
	}
	defer rows.Close()
	for rows.Next() {
		var item briefingRecurring
		if err := rows.Scan(&item.Signature, &item.Count, &item.Sessions, &item.LastAt); err != nil {
			return out, err
		}
		item.SampleLine = frictionSignatureLine(item.Signature)
		if hint := friction.LookupHint(item.Signature); hint != nil {
			item.Mechanism, item.MechanismEN = hint.Mechanism, hint.MechanismEN
		}
		out.Recurring = append(out.Recurring, item)
	}
	if err := rows.Err(); err != nil {
		return out, err
	}
	// The mined endings ride along per signature — only the corroborated top,
	// because a briefing repeats nothing it cannot back.
	for index := range out.Recurring {
		resolution, err := s.mineResolution(ctx, out.Recurring[index].Signature, projectKey)
		if err != nil {
			return out, err
		}
		if len(resolution.Actions) > 0 && resolution.Actions[0].Sessions >= 2 {
			out.Recurring[index].TopEnding = resolution.Actions[0].Label
			out.Recurring[index].EndingScope = resolution.Actions[0].Sessions
		}
	}

	fileRows, err := s.db.QueryContext(ctx, `
		SELECT sf.path, COUNT(*), COUNT(DISTINCT sf.session_id)
		FROM session_files sf JOIN sessions s ON s.id = sf.session_id
		WHERE s.project_key = ? AND sf.action = 'read'
		GROUP BY sf.path ORDER BY COUNT(*) DESC LIMIT ?`, projectKey, briefingFilesLimit)
	if err != nil {
		return out, err
	}
	defer fileRows.Close()
	for fileRows.Next() {
		var item briefingHotFile
		if err := fileRows.Scan(&item.Path, &item.Reads, &item.Sessions); err != nil {
			return out, err
		}
		out.HotFiles = append(out.HotFiles, item)
	}
	return out, fileRows.Err()
}

// briefingMarkdown renders the briefing for a context window: terse, factual,
// the calibers at the bottom.
func briefingMarkdown(briefing briefingResponse) string {
	var b strings.Builder
	label := briefing.ProjectKey
	if index := strings.LastIndexAny(label, "/\\"); index >= 0 && index+1 < len(label) {
		label = label[index+1:]
	}
	fmt.Fprintf(&b, "# 项目开工简报 · %s\n\n", label)
	if briefing.SessionsKnown == 0 {
		b.WriteString("本机历史中没有这个项目的会话记录——下面没有可给出的事实，这不是错误。\n")
		return b.String()
	}
	fmt.Fprintf(&b, "> 来源：本机 %d 个会话的记录 · 生成于 %s\n\n", briefing.SessionsKnown, briefing.GeneratedAt)

	if len(briefing.WorkingCommands) > 0 {
		b.WriteString("## 怎么干活（作业命令，按会话佐证数）\n\n")
		for _, item := range briefing.WorkingCommands {
			failures := "未记录到失败"
			if item.Failures > 0 {
				failures = fmt.Sprintf("%d 次记录到失败", item.Failures)
			}
			fmt.Fprintf(&b, "- `%s` — %d 个会话 · %d 次 · %s\n", item.Label, item.Sessions, item.Runs, failures)
		}
		b.WriteString("\n")
	}
	if len(briefing.Recurring) > 0 {
		b.WriteString("## 这里常撞的（反复摩擦，≥2 个会话）\n\n")
		for _, item := range briefing.Recurring {
			fmt.Fprintf(&b, "- **%s** — %d 个会话 · %d 次\n", item.SampleLine, item.Sessions, item.Count)
			if item.Mechanism != "" {
				fmt.Fprintf(&b, "  机制：%s\n", item.Mechanism)
			}
			if item.TopEnding != "" {
				fmt.Fprintf(&b, "  历史上终结后最常见动作：`%s`（%d 个会话佐证）\n", item.TopEnding, item.EndingScope)
			}
		}
		b.WriteString("\n")
	}
	if len(briefing.HotFiles) > 0 {
		b.WriteString("## 状态在哪些文件里（热点文件，按读取记录）\n\n")
		for _, item := range briefing.HotFiles {
			fmt.Fprintf(&b, "- %s — %d 个会话读了 %d 次\n", item.Path, item.Sessions, item.Reads)
		}
		b.WriteString("\n")
	}
	if len(briefing.WorkingCommands) == 0 && len(briefing.Recurring) == 0 && len(briefing.HotFiles) == 0 {
		b.WriteString("有会话记录，但尚无满足佐证门槛的事实（作业命令需 ≥3 次 ≥2 会话；摩擦需 ≥2 会话）。佐证会随历史累积。\n\n")
	}
	fmt.Fprintf(&b, "---\n%s\n", briefing.Note)
	return b.String()
}
